language: erlang
otp_release:
   - R15B01
   - R15B
   - R14B04
   - R14B03
   - R14B02


before_install:
  - "git clone git://github.com/evanmiller/ChicagoBoss.git"
  - "cd ChicagoBoss"
  - "make"
  - "cd .."
  
before_script:
  - "sh init.sh start"
  
script: "cucumber"

after_script:
  - "sh init.sh stop"