%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('value', {anyAttribs, 'value'}).
-record('mergeMap', {anyAttribs, 'href'}).
-record('resourceRef', {anyAttribs, 'href'}).
-record('topicRef', {anyAttribs, 'href'}).
-record('role', {anyAttribs, 'reifier', 'itemIdentity', 'type', 'topicRef'}).
-record('association', {anyAttribs, 'reifier', 'itemIdentity', 'type', 'scope', 'role'}).
-record('occurrence', {anyAttribs, 'reifier', 'itemIdentity', 'type', 'scope', value}).
-record('type', {anyAttribs, 'topicRef'}).
-record('instanceOf', {anyAttribs, 'topicRef'}).
-record('scope', {anyAttribs, 'topicRef'}).
-record('variant', {anyAttribs, 'reifier', 'itemIdentity', 'scope', value}).
-record('name', {anyAttribs, 'reifier', 'itemIdentity', 'type', 'scope', 'value', 'variant'}).
-record('subjectIdentifier', {anyAttribs, 'href'}).
-record('subjectLocator', {anyAttribs, 'href'}).
-record('itemIdentity', {anyAttribs, 'href'}).
-record('topic', {anyAttribs, 'id', identifier, 'instanceOf', occurrencesandnames}).
-record('topicMap', {anyAttribs, 'reifier', 'version', 'itemIdentity', 'mergeMap', topicsandassosciations}).
-record('any-markup', {anyAttribs, 'datatype', any}).
